### ISSUE TITLE
GuixSD installer for Emacs nerds

### ISSUE THREAD

**Issue by wigust** [alezost/guix.el#11]
Just in idea stage

![Screenshot](https://i.imgur.com/eqW5sE2.png)

https://github.com/wigust/guix.el/tree/guixsd-installer

**Comment by alezost** [comment]
Wow, Emacs installer!  This sounds like an ambitious project, but I think Emacs-Guix is not a proper place for it.  Since it would install Guix, making it a part of Guix itself sounds natural for me, besides there are `wip-installer` and [wip-installer-2](http://git.savannah.gnu.org/cgit/guix.git/log/?h=wip-installer-2) branches in the Guix repo (with the ncurses interface).

So I think if you suggest to add the Emacs installer to the Guix repo, it will surely be agreed.

**Comment by tumashu** [comment]
cool!!!!!

**Comment by alezost** [comment]
Sorry, I am closing this issue.  As I wrote, I think this project should not be a part of Emacs-Guix.

**Comment by Ambrevar** [comment]
@wigust Any progress?  I'd love to see this go upstream :)
