### ISSUE TITLE
Need help about C-c . b

### ISSUE THREAD

**Issue by tumashu** [alezost/guix.el#4]
When I C-c .b, the problem is showed like below:
```
scheme@(guile-user)> (begin
      (guix-warning-port (current-warning-port))
      (current-build-output-port (current-error-port)))
$2 = #<output: file 9da3f18>
scheme@(guile-user)> ,run-in-store (build-package emacs-exwm-x #:use-substitutes? #t #:dry-run? #f)
While executing meta-command:
ERROR: Throw to key `srfi-34' with args `(#<condition &message [message: "gcc-arm-bug-71399.patch: patch not found"] 9b3acb0>)'.
scheme@(guile-user)> 
```
Any suggestion? The below is my guix config
```
(require 'guix)
(require 'geiser-guile)

(global-guix-prettify-mode)

(setq geiser-debug-jump-to-debug-p nil)

(setq guix-directory "~/project/guix")

(with-eval-after-load 'geiser-guile
  (add-to-list 'geiser-guile-load-path "~/.config/guix/latest/")
  ;; (add-to-list 'geiser-guile-load-path "~/project/guix/")
  )

(add-hook 'scheme-mode-hook 'guix-devel-mode)

```

**Comment by alezost** [comment]
Hello, sorry for the delay, I've just noticed this issue.

I see, this is a confusing problem.  Try to remove the
trailing slash in this line:

``(add-to-list 'geiser-guile-load-path "~/.config/guix/latest/")``

I.e. replace it with:

``(add-to-list 'geiser-guile-load-path "~/.config/guix/latest")``

I would say this is a general problem with Guile: file names are
constructed with `string-append` without checking for trailing
slashes, so often you end up with things like `/bad//path` or
`/badpath` instead of `/bad/path`.

In this particular case, the following happens: Guix tries to find
patches relative to Guile load path directories, by appending
`/gnu/packages/patches` (see how it is done in the [%patch-path
variable](http://git.savannah.gnu.org/cgit/guix.git/tree/gnu/packages.scm#n133)),
but your `guix/latest/` name already contains the trailing slash, so the
final directory becomes `.../guix/latest//gnu/packages/patches` which
obviously doesn't exist.


By the way:

> (require 'guix)
> (require 'geiser-guile)

These 2 lines are not needed: they just slow down your Emacs
start time.  Also such requiring is error-prone because when you
have ``(require 'foo)`` and `foo` feature does not exist, Emacs
will break on that line.  If you really need to require anything,
you can do ``(require 'foo nil t)`` to avoid potential error if
`foo` does not exist.

But in this case requiring is really not needed, you can just
remove those 2 lines.

> (global-guix-prettify-mode)

Instead, I recommend to do it like this:

``(add-hook 'after-init-hook 'global-guix-prettify-mode)``

(Oops, I need to adjust the manual for this :smile:)

**Comment by tumashu** [comment]
Wow， how trick this problem is， thanks very much:-)

**Comment by alezost** [comment]
No problem :-)
