### ISSUE TITLE
About %load-path

### ISSUE THREAD

**Issue by tumashu** [alezost/guix.el#5]
My question is: the first two path come from where? they are always in the begin of list
```
Enter `,help' for help.
scheme@(guile-user)> %load-path
$2 = ("/home/feng/.config/guix/latest" "/home/feng/.emacs.d/elpa/geiser-20170704.1044/scheme/guile/" "~/.config/guix/latest" "/home/feng/.emacs.d/elpa/geiser-20170704.1044/scheme/guile" "/run/current-system/profile/share/guile/site/2.2" "/gnu/store/jkhydh37k4dcrw3mhcv2hlcipalmpblf-guile-2.2.2/share/guile/2.2" "/gnu/store/jkhydh37k4dcrw3mhcv2hlcipalmpblf-guile-2.2.2/share/guile/site/2.2" "/gnu/store/jkhydh37k4dcrw3mhcv2hlcipalmpblf-guile-2.2.2/share/guile/site" "/gnu/store/jkhydh37k4dcrw3mhcv2hlcipalmpblf-guile-2.2.2/share/guile")
scheme@(guile-user)> 
```
This is my config:
```
(use-package guix
  :ensure nil
  :config
  (setq guix-directory "~/project/guix")
  (setq geiser-debug-jump-to-debug-p nil)
  (add-hook 'after-init-hook 'global-guix-prettify-mode)
  (add-hook 'scheme-mode-hook 'guix-devel-mode)
  (with-eval-after-load 'geiser-guile
    ;; NOTE: "~/.config/guix/latest/" is invaild,
    ;; use "~/.config/guix/latest" instead.
    (add-to-list 'geiser-guile-load-path
                 (concat (file-name-directory (locate-library "geiser.el"))
                         "scheme/guile"))
    (add-to-list 'geiser-guile-load-path "~/.config/guix/latest")))

```

**Comment by alezost** [comment]
Hi!  Sorry for the long delay, I have just noticed this issue :smile:

These 2 paths are added by Geiser:

- `/home/feng/.config/guix/latest`

  This comes from your `geiser-guile-load-path` variable

- `/home/feng/.emacs.d/elpa/geiser-20170704.1044/scheme/guile/`

  This directory contains internal Geiser modules that are required to run Geiser properly.  It is not possible to avoid it.  If you are interested, it is added by `geiser-guile--set-geiser-load-path` function.

... actually, I see that you duplicate this directory with your code:

> ```elisp
>  (add-to-list 'geiser-guile-load-path
>                 (concat (file-name-directory (locate-library "geiser.el"))
>                         "scheme/guile"))
> ```

This shouldn't be needed.  What happens if you remove this code?

**Comment by tumashu** [comment]
```
/home/feng/.emacs.d/elpa/geiser-20170704.1044/scheme/guile/
/home/feng/.emacs.d/elpa/geiser-20170704.1044/scheme/guile
```
Are the above two strings the same path for guile?

**Comment by alezost** [comment]
Yes, except the trailing slash may cause issues sometimes as you know from https://github.com/alezost/guix.el/issues/4

So there is no reason for you to add this directory in your emacs config.

**Comment by tumashu** [comment]
OK, thanks very much
