### ISSUE TITLE
"Guix REPL ... No prompt found!"  ( -> Emacs package unusable ? )

### ISSUE THREAD

**Issue by fenix011** [alezost/guix.el#57]
Package seems to get installed by

```
$ guix package -i emacs-guix
```

, yet when one goes M-x 'guix-installed-packages..." i get 

```
Starting Guix REPL ... No prompt found!
```
(let me add that a Guile REPL prompt is opened in another parallel buffer, though )

... thus, leaving the package unusable.

Thanks, thanks, thanks

**Comment by dcunited001** [comment]
i recently moved back to an emacs manifest (that I assumed I was on), so i started encountering issues. i must not have upgraded guix for awhile because this just started happening.

the package needs to be updated. apparently there were breaking changes upstream. here's some options for now:

+ `guix build emacs-guix --with-latest=emacs-guix` may work, but not with a simple specifications->manifest. 
+ overriding the package in a personal channel to build from master would also work
+ using straight to install the package. it pulls from master unless specified (afaik)

there are likely other solutions. guix is pretty flexible. 

this package is pretty essential for noobs like me though.
